# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64fefd2d69f5528eb649b5dde846b555ee34815b3a84f0118f820d031719f6d10d62b21057bad9c1546c717f8e03f1bd153ddcde59fd97248a8e3fe4a6995c8a

test:
  secret_key_base: c38fadbaa24402143bb098f333c59444d6b196cc6a9742bc86d0ada1b6317a6630af298ab94ec80e934ffd0bc664a4ec96937d35157424a40e69a33164c3ee9f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
